version: "3.3"

services:
  postgres:
    container_name: db
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: animaltrax
      POSTGRES_USER: animaltrax
      POSTGRES_DB: animaltrax